#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch wofi with alt config

CONFIG="$HOME/.config/wayfire/wofi/config"
STYLE="$HOME/.config/wayfire/wofi/style.css"

if [[ ! `pidof wofi` ]]; then
	wofi --show drun --prompt 'Search Applications' --conf ${CONFIG} --style ${STYLE}
else
	pkill wofi
fi
