#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Arc-Evopop'
ICONS='Sardi-Evopop'
FONT='Noto Sans 11'
CURSOR='Catppuccin-Blue-Cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
