#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in River

WALLPAPER="$HOME/.config/river/wallpapers/wallpaper.png"

swaybg --output '*' --mode fill --image "$WALLPAPER"
